cmake_minimum_required(VERSION 3.8)
project(lart_msgs)

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(builtin_interfaces REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/ButtonEvent.msg"
  "msg/EncoderDelta.msg"
  "msg/CanFrame.msg"
  "msg/DashboardState.msg"
  "msg/Acu.msg"
  "msg/AppsAdcRaw.msg"
  "msg/Aqt1.msg"
  "msg/Aqt2.msg"
  "msg/Aqt3.msg"
  "msg/Aqt4.msg"
  "msg/Aqt5.msg"
  "msg/Aqt6.msg"
  "msg/Aqt7.msg"
  "msg/Aqt8.msg"
  "msg/AsfSignals.msg"
  "msg/CentralRear.msg"
  "msg/CubemarsFeedback.msg"
  "msg/CubemarsPositionLoop.msg"
  "msg/Dashboard.msg"
  "msg/DataBox.msg"
  "msg/DvDynamics1.msg"
  "msg/DvDynamics2.msg"
  "msg/DvStatus.msg"
  "msg/FrontWheelL.msg"
  "msg/FrontWheelR.msg"
  "msg/Hv500AcDcCurrent.msg"
  "msg/Hv500ErpmDutyVoltage.msg"
  "msg/Hv500Foc.msg"
  "msg/Hv500Minmaxaccurrent.msg"
  "msg/Hv500Minmaxdccurrent.msg"
  "msg/Hv500Misc.msg"
  "msg/Hv500Setaccurrent.msg"
  "msg/Hv500Setbrakecurrent.msg"
  "msg/Hv500Setdigoutput.msg"
  "msg/Hv500Setdriveenable.msg"
  "msg/Hv500Seterpm.msg"
  "msg/Hv500Setmaxacbrakecurrent.msg"
  "msg/Hv500Setmaxaccurrent.msg"
  "msg/Hv500Setmaxdcbrakecurrent.msg"
  "msg/Hv500Setmaxdccurrent.msg"
  "msg/Hv500Setposition.msg"
  "msg/Hv500Setrelbrakecurrent.msg"
  "msg/Hv500Setrelcurrent.msg"
  "msg/Hv500Targetiq.msg"
  "msg/Hv500Temperatures.msg"
  "msg/IvtMsgCmd.msg"
  "msg/IvtMsgResponse.msg"
  "msg/IvtMsgResultAs.msg"
  "msg/IvtMsgResultI.msg"
  "msg/IvtMsgResultT.msg"
  "msg/IvtMsgResultU1.msg"
  "msg/IvtMsgResultU2.msg"
  "msg/IvtMsgResultU3.msg"
  "msg/IvtMsgResultW.msg"
  "msg/IvtMsgResultWh.msg"
  "msg/Jetson.msg"
  "msg/MasterMscId1.msg"
  "msg/MasterMscId2.msg"
  "msg/MasterMscId3.msg"
  "msg/MasterMscId4.msg"
  "msg/MasterPrechargeId1.msg"
  "msg/MasterSocAccumulator.msg"
  "msg/PedalBox.msg"
  "msg/RearWheelL.msg"
  "msg/RearWheelR.msg"
  "msg/Res.msg"
  "msg/SlamStatsCan.msg"
  "msg/Slave01MscId1.msg"
  "msg/Slave01MscId2.msg"
  "msg/Slave01TemperatureId1.msg"
  "msg/Slave01TemperatureId2.msg"
  "msg/Slave01VoltageId1.msg"
  "msg/Slave01VoltageId2.msg"
  "msg/Slave01VoltageId3.msg"
  "msg/Slave02MscId1.msg"
  "msg/Slave02MscId2.msg"
  "msg/Slave02TemperatureId1.msg"
  "msg/Slave02TemperatureId2.msg"
  "msg/Slave02VoltageId1.msg"
  "msg/Slave02VoltageId2.msg"
  "msg/Slave02VoltageId3.msg"
  "msg/Slave03MscId1.msg"
  "msg/Slave03MscId2.msg"
  "msg/Slave03TemperatureId1.msg"
  "msg/Slave03TemperatureId2.msg"
  "msg/Slave03VoltageId1.msg"
  "msg/Slave03VoltageId2.msg"
  "msg/Slave03VoltageId3.msg"
  "msg/Slave04MscId1.msg"
  "msg/Slave04MscId2.msg"
  "msg/Slave04TemperatureId1.msg"
  "msg/Slave04TemperatureId2.msg"
  "msg/Slave04VoltageId1.msg"
  "msg/Slave04VoltageId2.msg"
  "msg/Slave04VoltageId3.msg"
  "msg/Slave05MscId1.msg"
  "msg/Slave05MscId2.msg"
  "msg/Slave05TemperatureId1.msg"
  "msg/Slave05TemperatureId2.msg"
  "msg/Slave05VoltageId1.msg"
  "msg/Slave05VoltageId2.msg"
  "msg/Slave05VoltageId3.msg"
  "msg/Slave06MscId1.msg"
  "msg/Slave06MscId2.msg"
  "msg/Slave06TemperatureId1.msg"
  "msg/Slave06TemperatureId2.msg"
  "msg/Slave06VoltageId1.msg"
  "msg/Slave06VoltageId2.msg"
  "msg/Slave06VoltageId3.msg"
  "msg/Slave07MscId1.msg"
  "msg/Slave07MscId2.msg"
  "msg/Slave07TemperatureId1.msg"
  "msg/Slave07TemperatureId2.msg"
  "msg/Slave07VoltageId1.msg"
  "msg/Slave07VoltageId2.msg"
  "msg/Slave07VoltageId3.msg"
  "msg/Slave08MscId1.msg"
  "msg/Slave08MscId2.msg"
  "msg/Slave08TemperatureId1.msg"
  "msg/Slave08TemperatureId2.msg"
  "msg/Slave08VoltageId1.msg"
  "msg/Slave08VoltageId2.msg"
  "msg/Slave08VoltageId3.msg"
  "msg/Slave09MscId1.msg"
  "msg/Slave09MscId2.msg"
  "msg/Slave09TemperatureId1.msg"
  "msg/Slave09TemperatureId2.msg"
  "msg/Slave09VoltageId1.msg"
  "msg/Slave09VoltageId2.msg"
  "msg/Slave09VoltageId3.msg"
  "msg/Slave10MscId1.msg"
  "msg/Slave10MscId2.msg"
  "msg/Slave10TemperatureId1.msg"
  "msg/Slave10TemperatureId2.msg"
  "msg/Slave10VoltageId1.msg"
  "msg/Slave10VoltageId2.msg"
  "msg/Slave10VoltageId3.msg"
  "msg/Slave11MscId1.msg"
  "msg/Slave11MscId2.msg"
  "msg/Slave11TemperatureId1.msg"
  "msg/Slave11TemperatureId2.msg"
  "msg/Slave11VoltageId1.msg"
  "msg/Slave11VoltageId2.msg"
  "msg/Slave11VoltageId3.msg"
  "msg/Slave12MscId1.msg"
  "msg/Slave12MscId2.msg"
  "msg/Slave12TemperatureId1.msg"
  "msg/Slave12TemperatureId2.msg"
  "msg/Slave12VoltageId1.msg"
  "msg/Slave12VoltageId2.msg"
  "msg/Slave12VoltageId3.msg"
  "msg/StartBalancing.msg"
  "msg/StartCharging.msg"
  "msg/StartPrecharge.msg"
  "msg/StartProgrammer.msg"
  "msg/VcuHv.msg"
  "msg/VcuIgnR2d.msg"
  "msg/VcuRpm.msg"
  "msg/VcuRpmTarget.msg"
  "msg/VcuStates.msg"
  "msg/VcuTorqueTarget.msg"
  DEPENDENCIES builtin_interfaces
)

ament_package()
