// Auto-generated from DBC files by generate_dbc_api.py. Do not edit.
#ifndef LART_DBC_API_H
#define LART_DBC_API_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    struct {
        float acu_cpu_temp;
        float acu_state;
        float as_state;
        float asms;
        float assi_state;
        float emergency;
        float emergency_cause;
        float ign;
        float mission_select;
    } acu;
    struct {
        float apps1_raw;
        float apps2_raw;
    } apps_adc_raw;
    struct {
        float bots;
        float frt_brk_press;
        float res;
    } aqt1;
    struct {
        float brake_temp;
        float tire_temp;
        float wheel_spd;
    } aqt2;
    struct {
        float brake_temp;
        float tire_temp;
        float wheel_spd;
    } aqt3;
    struct {
        float emergency;
        float inertia;
        float st_angle;
        float susp_l;
        float susp_r;
    } aqt4;
    struct {
        float brake_temp;
        float tire_temp;
    } aqt5;
    struct {
        float brake_temp;
        float tire_temp;
    } aqt6;
    struct {
        float rear_brk_press;
        float susp_l;
        float susp_r;
    } aqt7;
    struct {
        float ntc1;
        float ntc2;
        float ntc3;
    } aqt8;
    struct {
        float brake_pressure_front;
        float brake_pressure_rear;
        float ebs_pressure_tank_front;
        float ebs_pressure_tank_rear;
    } asf_signals;
    struct {
        float current;
        float driver_temp;
        float error_code;
        float position;
        float speed_rpm;
    } cubemars_feedback;
    struct {
        float position;
    } cubemars_position_loop;
    struct {
        float ignition_switch_raw;
        float r2d_button_raw;
    } dashboard;
    struct {
        float brake_hydr_actual;
        float brake_hydr_target;
        float motor_moment_actual;
        float motor_moment_target;
        float speed_actual;
        float speed_target;
        float steering_angle_actual;
        float steering_angle_target;
    } dv_dynamics_1;
    struct {
        float acceleration_lateral;
        float acceleration_longitudinal;
        float yaw_rate;
    } dv_dynamics_2;
    struct {
        float ami_state;
        float as_status;
        float asb_ebs_state;
        float asb_redundancy_state;
        float cones_count_actual;
        float cones_count_all;
        float lap_counter;
        float steering_state;
    } dv_status;
    struct {
        float inv1_actual_accurrent;
        float inv1_actual_dccurrent;
    } inv1_ac_dc_current;
    struct {
        float inv1_actual_duty;
        float inv1_actual_erpm;
        float inv1_actual_inputvoltage;
    } inv1_erpm_duty_voltage;
    struct {
        float inv1_actual_foc_id;
        float inv1_actual_foc_iq;
    } inv1_foc;
    struct {
        float inv1_availablemaxaccurrent;
        float inv1_availableminaccurrent;
        float inv1_maxaccurrent;
        float inv1_minaccurrent;
    } inv1_minmaxaccurrent;
    struct {
        float inv1_availablemaxdccurrent;
        float inv1_availablemindccurrent;
        float inv1_maxdccurrent;
        float inv1_mindccurrent;
    } inv1_minmaxdccurrent;
    struct {
        float inv1_actual_brake;
        float inv1_actual_throttle;
        float inv1_can_map_version;
        float inv1_capacitor_temp_limit;
        float inv1_dc_current_limit;
        float inv1_digital_input_1;
        float inv1_digital_input_2;
        float inv1_digital_input_3;
        float inv1_digital_input_4;
        float inv1_digital_output_1;
        float inv1_digital_output_2;
        float inv1_digital_output_3;
        float inv1_digital_output_4;
        float inv1_drive_enable;
        float inv1_drive_enable_limit;
        float inv1_igbt_accel_limit;
        float inv1_igbt_temp_limit;
        float inv1_input_voltage_limit;
        float inv1_motor_accel_limit;
        float inv1_motor_temp_limit;
        float inv1_power_limit;
        float inv1_rpm_max_limit;
        float inv1_rpm_min_limit;
    } inv1_misc;
    struct {
        float inv1_cmd_targetaccurrent;
    } inv1_setaccurrent;
    struct {
        float inv1_cmd_targetbrakecurrent;
    } inv1_setbrakecurrent;
    struct {
        float inv1_cmd_setdigoutput1;
        float inv1_cmd_setdigoutput2;
        float inv1_cmd_setdigoutput3;
        float inv1_cmd_setdigoutput4;
    } inv1_setdigoutput;
    struct {
        float inv1_cmd_driveenable;
    } inv1_setdriveenable;
    struct {
        float inv1_cmd_targetspeed;
    } inv1_seterpm;
    struct {
        float inv1_cmd_maxacbrakecurrent;
    } inv1_setmaxacbrakecurrent;
    struct {
        float inv1_cmd_maxaccurrent;
    } inv1_setmaxaccurrent;
    struct {
        float inv1_cmd_maxdcbrakecurrent;
    } inv1_setmaxdcbrakecurrent;
    struct {
        float inv1_cmd_maxdccurrent;
    } inv1_setmaxdccurrent;
    struct {
        float inv1_cmd_targetposition;
    } inv1_setposition;
    struct {
        float inv1_cmd_tgtrelbrakecurrent;
    } inv1_setrelbrakecurrent;
    struct {
        float inv1_cmd_targetrelativecurrent;
    } inv1_setrelcurrent;
    struct {
        float inv1_controlmode;
        float inv1_ismotorstill;
        float inv1_motorposition;
        float inv1_targetiq;
    } inv1_targetiq;
    struct {
        float inv1_actual_faultcode;
        float inv1_actual_tempcontroller;
        float inv1_actual_tempmotor;
        float inv1_tempinverter;
        float inv1_tempmotor;
    } inv1_temperatures;
    struct {
        float inv2_actual_accurrent;
        float inv2_actual_dccurrent;
    } inv2_ac_dc_current;
    struct {
        float inv2_actual_duty;
        float inv2_actual_erpm;
        float inv2_actual_inputvoltage;
    } inv2_erpm_duty_voltage;
    struct {
        float inv2_actual_foc_id;
        float inv2_actual_foc_iq;
    } inv2_foc;
    struct {
        float inv2_availablemaxaccurrent;
        float inv2_availableminaccurrent;
        float inv2_maxaccurrent;
        float inv2_minaccurrent;
    } inv2_minmaxaccurrent;
    struct {
        float inv2_availablemaxdccurrent;
        float inv2_availablemindccurrent;
        float inv2_maxdccurrent;
        float inv2_mindccurrent;
    } inv2_minmaxdccurrent;
    struct {
        float inv2_actual_brake;
        float inv2_actual_throttle;
        float inv2_can_map_version;
        float inv2_capacitor_temp_limit;
        float inv2_dc_current_limit;
        float inv2_digital_input_1;
        float inv2_digital_input_2;
        float inv2_digital_input_3;
        float inv2_digital_input_4;
        float inv2_digital_output_1;
        float inv2_digital_output_2;
        float inv2_digital_output_3;
        float inv2_digital_output_4;
        float inv2_drive_enable;
        float inv2_drive_enable_limit;
        float inv2_igbt_accel_limit;
        float inv2_igbt_temp_limit;
        float inv2_input_voltage_limit;
        float inv2_motor_accel_limit;
        float inv2_motor_temp_limit;
        float inv2_power_limit;
        float inv2_rpm_max_limit;
        float inv2_rpm_min_limit;
    } inv2_misc;
    struct {
        float inv2_cmd_targetaccurrent;
    } inv2_setaccurrent;
    struct {
        float inv2_cmd_targetbrakecurrent;
    } inv2_setbrakecurrent;
    struct {
        float inv2_cmd_setdigoutput1;
        float inv2_cmd_setdigoutput2;
        float inv2_cmd_setdigoutput3;
        float inv2_cmd_setdigoutput4;
    } inv2_setdigoutput;
    struct {
        float inv2_cmd_driveenable;
    } inv2_setdriveenable;
    struct {
        float inv2_cmd_targetspeed;
    } inv2_seterpm;
    struct {
        float inv2_cmd_maxacbrakecurrent;
    } inv2_setmaxacbrakecurrent;
    struct {
        float inv2_cmd_maxaccurrent;
    } inv2_setmaxaccurrent;
    struct {
        float inv2_cmd_maxdcbrakecurrent;
    } inv2_setmaxdcbrakecurrent;
    struct {
        float inv2_cmd_maxdccurrent;
    } inv2_setmaxdccurrent;
    struct {
        float inv2_cmd_targetposition;
    } inv2_setposition;
    struct {
        float inv2_cmd_tgtrelbrakecurrent;
    } inv2_setrelbrakecurrent;
    struct {
        float inv2_cmd_targetrelativecurrent;
    } inv2_setrelcurrent;
    struct {
        float inv2_controlmode;
        float inv2_ismotorstill;
        float inv2_motorposition;
        float inv2_targetiq;
    } inv2_targetiq;
    struct {
        float inv2_actual_faultcode;
        float inv2_actual_tempcontroller;
        float inv2_actual_tempmotor;
        float inv2_tempinverter;
        float inv2_tempmotor;
    } inv2_temperatures;
    struct {
        float ivt_id_cmd;
        float val_10_set_can_id_sn_i;
        float val_10_set_can_id_val_i;
        float val_11_set_can_id_sn_u1;
        float val_11_set_can_id_val_u1;
        float val_12_set_can_id_sn_u2;
        float val_12_set_can_id_val_u2;
        float val_13_set_can_id_sn_u3;
        float val_13_set_can_id_val_u3;
        float val_14_set_can_id_sn_t;
        float val_14_set_can_id_val_t;
        float val_15_set_can_id_sn_w;
        float val_15_set_can_id_val_w;
        float val_16_set_can_id_sn_as;
        float val_16_set_can_id_val_as;
        float val_17_set_can_id_sn_wh;
        float val_17_set_can_id_val_wh;
        float val_1d_set_can_id_sn_command;
        float val_1d_set_can_id_val_command;
        float val_1f_set_can_id_sn_response;
        float val_1f_set_can_id_val_response;
        float val_20_conf_cycletime_i;
        float val_20_conf_endianess_i;
        float val_20_conf_sign_i;
        float val_20_conf_triggermode_i;
        float val_21_conf_cycletime_u1;
        float val_21_conf_endianess_u1;
        float val_21_conf_sign_u1;
        float val_21_conf_triggermode_u1;
        float val_22_conf_cycletime_u2;
        float val_22_conf_endianess_u2;
        float val_22_conf_sign_u2;
        float val_22_conf_triggermode_u2;
        float val_23_conf_cycletime_u3;
        float val_23_conf_endianess_u3;
        float val_23_conf_sign_u3;
        float val_23_conf_triggermode_u3;
        float val_24_conf_cycletime_t;
        float val_24_conf_endianess_t;
        float val_24_conf_sign_t;
        float val_24_conf_triggermode_t;
        float val_25_conf_cycletime_w;
        float val_25_conf_endianess_w;
        float val_25_conf_sign_w;
        float val_25_conf_triggermode_w;
        float val_26_conf_cycletime_as;
        float val_26_conf_endianess_as;
        float val_26_conf_sign_as;
        float val_26_conf_triggermode_as;
        float val_27_conf_cycletime_wh;
        float val_27_conf_endianess_wh;
        float val_27_conf_sign_wh;
        float val_27_conf_triggermode_wh;
        float val_30_reset_device_sn;
        float val_30_reset_item;
        float val_31_00_trigger_i;
        float val_31_01_trigger_u1;
        float val_31_02_trigger_u2;
        float val_31_03_trigger_u3;
        float val_31_04_trigger_t;
        float val_31_05_trigger_w;
        float val_31_06_trigger_as;
        float val_31_07_trigger_wh;
        float val_31_trigger_spare;
        float val_32_store_dummy;
        float val_33_oc_test_time;
        float val_34_actual_mode;
        float val_34_code_level;
        float val_34_startup_mode;
        float val_35_oc_pos_reset_threshold;
        float val_35_oc_pos_set_threshold;
        float val_36_oc_neg_reset_threshold;
        float val_36_oc_neg_set_threshold;
        float val_3a_restart_to_bitrate;
        float val_3d_restart_default_dummy;
        float val_3f_restart_dummy;
        float val_40_get_measerror_item;
        float val_41_get_systemerror_item;
        float val_42_get_alllogdata_item;
        float val_43_get_logdata_item;
        float val_50_get_can_id_sn_i;
        float val_51_get_can_id_sn_u1;
        float val_52_get_can_id_sn_u2;
        float val_53_get_can_id_sn_u3;
        float val_54_get_can_id_sn_t;
        float val_55_get_can_id_sn_w;
        float val_56_get_can_id_sn_as;
        float val_57_get_can_id_sn_wh;
        float val_5d_get_can_id_sn_command;
        float val_5f_get_can_id_sn_response;
        float val_60_get_result_dummy_i;
        float val_61_get_result_dummy_u1;
        float val_62_get_result_dummy_u2;
        float val_63_get_result_dummy_u3;
        float val_64_get_result_dummy_t;
        float val_65_get_result_dummy_w;
        float val_66_get_result_dummy_as;
        float val_67_get_result_dummy_wh;
        float val_73_get_oc_test_dummy;
        float val_74_get_mode_dummy;
        float val_75_get_oc_pos_dummy;
        float val_76_get_oc_neg_dummy;
        float val_79_get_device_id_dummy;
        float val_7a_get_sw_version_dummy;
        float val_7b_get_serien_nr_dummy;
        float val_7c_get_art_nr_dummy;
    } ivt_msg_cmd;
    struct {
        float a0_resp_cycletime_i;
        float a0_resp_endianess_i;
        float a0_resp_sign_i;
        float a0_resp_triggermode_i;
        float a1_resp_cycletime_u1;
        float a1_resp_endianess_u1;
        float a1_resp_sign_u1;
        float a1_resp_triggermode_u1;
        float a2_resp_cycletime_u2;
        float a2_resp_endianess_u2;
        float a2_resp_sign_u2;
        float a2_resp_triggermode_u2;
        float a3_resp_cycletime_u3;
        float a3_resp_endianess_u3;
        float a3_resp_sign_u3;
        float a3_resp_triggermode_u3;
        float a4_resp_cycletime_t;
        float a4_resp_endianess_t;
        float a4_resp_sign_t;
        float a4_resp_triggermode_t;
        float a5_resp_cycletime_w;
        float a5_resp_endianess_w;
        float a5_resp_sign_w;
        float a5_resp_triggermode_w;
        float a6_resp_cycletime_as;
        float a6_resp_endianess_as;
        float a6_resp_sign_as;
        float a6_resp_triggermode_as;
        float a7_resp_cycletime_wh;
        float a7_resp_endianess_wh;
        float a7_resp_sign_wh;
        float a7_resp_triggermode_wh;
        float b0_resp_reset_device_sn;
        float b0_resp_reset_item;
        float b1_00_trigger_i;
        float b1_01_trigger_u1;
        float b1_02_trigger_u2;
        float b1_03_trigger_u3;
        float b1_04_trigger_t;
        float b1_05_trigger_w;
        float b1_06_trigger_as;
        float b1_07_trigger_wh;
        float b1_trigger_spare;
        float b2_resp_store_device_sn;
        float b2_resp_store_dummy;
        float b3_resp_oc_test_time;
        float b4_resp_actual_mode;
        float b4_resp_code_level;
        float b4_resp_startup_mode;
        float b5_resp_oc_pos_reset_threshold;
        float b5_resp_oc_pos_set_threshold;
        float b6_resp_oc_neg_reset_threshold;
        float b6_resp_oc_neg_set_threshold;
        float b9_resp_device_com;
        float b9_resp_device_current;
        float b9_resp_device_toi;
        float b9_resp_device_type;
        float b9_resp_device_v_supply;
        float b9_resp_device_voltage_chan;
        float ba_resp_sw_ver_day;
        float ba_resp_sw_ver_internal;
        float ba_resp_sw_ver_major_hw;
        float ba_resp_sw_ver_minor;
        float ba_resp_sw_ver_month;
        float ba_resp_sw_ver_revision;
        float ba_resp_sw_ver_vear;
        float bb_resp_serien_nr;
        float bc_resp_art_n;
        float bf_restart_alive_cmd_id;
        float bf_restart_alive_sn;
        float ff_wrong_command;
        float ivt_id_response;
        float val_80_resp_measerror_count_mask;
        float val_80_resp_measerror_item;
        float val_81_resp_systemerror_count_mask;
        float val_81_resp_systemerror_item;
        float val_82_resp_alllogdata_counter;
        float val_82_resp_alllogdata_item;
        float val_83_resp_logdata_counter;
        float val_83_resp_logdata_item;
        float val_90_resp_can_id_sn_i;
        float val_90_resp_can_id_val_i;
        float val_91_resp_can_id_sn_u1;
        float val_91_resp_can_id_val_u1;
        float val_92_resp_can_id_sn_u2;
        float val_92_resp_can_id_val_u2;
        float val_93_resp_can_id_sn_u3;
        float val_93_resp_can_id_val_u3;
        float val_94_resp_can_id_sn_t;
        float val_94_resp_can_id_val_t;
        float val_95_resp_can_id_sn_w;
        float val_95_resp_can_id_val_w;
        float val_96_resp_can_id_sn_as;
        float val_96_resp_can_id_val_as;
        float val_97_resp_can_id_sn_wh;
        float val_97_resp_can_id_val_wh;
        float val_9d_resp_can_id_sn_command;
        float val_9d_resp_can_id_val_command;
        float val_9f_resp_can_id_sn_response;
        float val_9f_resp_can_id_val_response;
    } ivt_msg_response;
    struct {
        float ivt_id_result_as;
        float ivt_msgcount_result_as;
        float ivt_result_as;
        float ivt_result_as_channel_error;
        float ivt_result_as_measurement_error;
        float ivt_result_as_ocs;
        float ivt_result_as_system_error;
    } ivt_msg_result_as;
    struct {
        float ivt_id_result_i;
        float ivt_msgcount_result_i;
        float ivt_result_i;
        float ivt_result_i_channel_error;
        float ivt_result_i_measurement_error;
        float ivt_result_i_ocs;
        float ivt_result_i_system_error;
    } ivt_msg_result_i;
    struct {
        float ivt_id_result_t;
        float ivt_msgcount_result_t;
        float ivt_result_t;
        float ivt_result_t_channel_error;
        float ivt_result_t_measurement_error;
        float ivt_result_t_ocs;
        float ivt_result_t_system_error;
    } ivt_msg_result_t;
    struct {
        float ivt_id_result_u1;
        float ivt_msgcount_result_u1;
        float ivt_result_u1;
        float ivt_result_u1_channel_error;
        float ivt_result_u1_measurement_error;
        float ivt_result_u1_ocs;
        float ivt_result_u1_system_error;
    } ivt_msg_result_u1;
    struct {
        float ivt_id_result_u2;
        float ivt_msgcount_result_u2;
        float ivt_result_u2;
        float ivt_result_u2_channel_error;
        float ivt_result_u2_measurement_error;
        float ivt_result_u2_ocs;
        float ivt_result_u2_system_error;
    } ivt_msg_result_u2;
    struct {
        float ivt_id_result_u3;
        float ivt_msgcount_result_u3;
        float ivt_result_u3;
        float ivt_result_u3_channel_error;
        float ivt_result_u3_measurement_error;
        float ivt_result_u3_ocs;
        float ivt_result_u3_system_error;
    } ivt_msg_result_u3;
    struct {
        float ivt_id_result_w;
        float ivt_msgcount_result_w;
        float ivt_result_w;
        float ivt_result_w_channel_error;
        float ivt_result_w_measurement_error;
        float ivt_result_w_ocs;
        float ivt_result_w_system_error;
    } ivt_msg_result_w;
    struct {
        float ivt_id_result_wh;
        float ivt_msgcount_result_wh;
        float ivt_result_wh;
        float ivt_result_wh_channel_error;
        float ivt_result_wh_measurement_error;
        float ivt_result_wh_ocs;
        float ivt_result_wh_system_error;
    } ivt_msg_result_wh;
    struct {
        float as_mission;
        float as_state;
        float cpu;
        float emergency_cause;
        float gpu;
        float temperature;
    } jetson;
    struct {
        float adbms_pec_error;
        float ams_current_draw;
        float fault_counter;
        float master_fan_pwm;
        float master_firmware_version;
        float master_state;
        float mcu_temperature;
        float mcu_vref;
    } master_msc_id_1;
    struct {
        float fault1_code;
        float fault1_index_type;
        float fault1_index_value;
        float fault2_code;
        float fault2_index_type;
        float fault2_index_value;
        float master_runtime;
    } master_msc_id_2;
    struct {
        float overall_maximum_temperature;
        float overall_maximum_voltage;
        float overall_minimum_temperature;
        float overall_minimum_voltage;
    } master_msc_id_3;
    struct {
        float slaves_detected;
    } master_msc_id_4;
    struct {
        float precharge_ctc_air_min_state;
        float precharge_ctc_air_pos_state;
        float precharge_ctc_charge_state;
        float precharge_ctc_discharge_state;
        float precharge_state;
    } master_precharge_id_1;
    struct {
        float soc_float;
        float soc_integer;
    } master_soc_accumulator;
    struct {
        float coolingfan_pwm;
        float waterpump_pwm;
    } pdm_cooling;
    struct {
        float lv_voltage_mv;
    } pdm_lv;
    struct {
        float signal;
    } res;
    struct {
        float cones_count_actual;
        float cones_count_all;
        float lap_counter;
    } slam_stats_can;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_01_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_overvoltage;
        float module_under_over_identifier;
        float module_undervoltage;
        float module_voltage_delta;
    } slave_01_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_01_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_01_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_01_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_01_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_01_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_02_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_overvoltage;
        float module_under_over_identifier;
        float module_undervoltage;
        float module_voltage_delta;
    } slave_02_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_02_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_02_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_02_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_02_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_02_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_03_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_03_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_03_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_03_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_03_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_03_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_03_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_04_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_04_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_04_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_04_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_04_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_04_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_04_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_05_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_05_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_05_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_05_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_05_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_05_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_05_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_06_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_06_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_06_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_06_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_06_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_06_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_06_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_07_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_07_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_07_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_07_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_07_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_07_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_07_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_08_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_08_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_08_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_08_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_08_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_08_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_08_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_09_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_09_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_09_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_09_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_09_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_09_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_09_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_10_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_10_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_10_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_10_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_10_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_10_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_10_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_11_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_11_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_11_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_11_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_11_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_11_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_11_voltage_id_3;
    struct {
        float module_voltage_avg;
        float module_voltage_max;
        float module_voltage_min;
        float module_voltage_sum;
    } slave_12_msc_id_1;
    struct {
        float module_ic_temperature;
        float module_ic_voltage;
        float module_open_wire;
        float module_voltage_delta;
    } slave_12_msc_id_2;
    struct {
        float temperature_value_1;
        float temperature_value_2;
        float temperature_value_3;
        float temperature_value_4;
    } slave_12_temperature_id_1;
    struct {
        float temperature_delta;
        float temperature_maximum;
        float temperature_value_5;
        float temperature_value_6;
    } slave_12_temperature_id_2;
    struct {
        float cell_voltage_1;
        float cell_voltage_2;
        float cell_voltage_3;
        float cell_voltage_4;
    } slave_12_voltage_id_1;
    struct {
        float cell_voltage_5;
        float cell_voltage_6;
        float cell_voltage_7;
        float cell_voltage_8;
    } slave_12_voltage_id_2;
    struct {
        float cell_voltage_10;
        float cell_voltage_11;
        float cell_voltage_12;
        float cell_voltage_9;
    } slave_12_voltage_id_3;
    struct {
        float balancing_request;
    } start_balancing;
    struct {
        float charging_request;
    } start_charging;
    struct {
        float precharge_request;
    } start_precharge;
    struct {
        float programming_request;
    } start_programmer;
    struct {
        float brake_pressure_front;
        float brake_pressure_rear;
        float hv;
    } vcu_hv;
    struct {
        float ignition_auto;
        float ignition_manual;
        float ignition_switch_raw;
        float r2d_auto;
        float r2d_button_raw;
        float r2d_manual;
        float shutdown_signal;
        float vcu_state;
    } vcu_ign_r2d;
    struct {
        float motor_current_left;
        float motor_current_right;
        float motor_rpm_left;
        float motor_rpm_right;
    } vcu_rpm;
    struct {
        float rpm_target;
    } vcu_rpm_target;
    struct {
        float vcu_state;
    } vcu_states;
    struct {
        float torque_target;
    } vcu_torque_target;
} DbcApi;

extern DbcApi dbc_api;

void check_dbc_errors(void (*on_error)(const char *id, const char *msg_name, const char *sig_name, float value, const char *choice_label));

#ifdef __cplusplus
}
#if defined(LART_UI_HAVE_RCLCPP) && LART_UI_HAVE_RCLCPP
#if defined(LART_HAVE_LART_MSGS) && LART_HAVE_LART_MSGS
#include <memory>
#include <vector>
#include <rclcpp/rclcpp.hpp>
void init_dbc_api_subscribers(std::shared_ptr<rclcpp::Node> node, std::vector<rclcpp::SubscriptionBase::SharedPtr>& subs);
#endif
#endif
#endif

#endif // LART_DBC_API_H
