#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations

// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_BRAKE_PEDAL_PRESSURE = 0,
    FLOW_GLOBAL_VARIABLE_ACCELL_PEDAL_PRESSURE = 1,
    FLOW_GLOBAL_VARIABLE_SOC = 2,
    FLOW_GLOBAL_VARIABLE_LV = 3,
    FLOW_GLOBAL_VARIABLE_READY = 4,
    FLOW_GLOBAL_VARIABLE_SPEED = 5,
    FLOW_GLOBAL_VARIABLE_TEMP_INV = 6,
    FLOW_GLOBAL_VARIABLE_TEMP_MOTOR = 7,
    FLOW_GLOBAL_VARIABLE_LOADING = 8,
    FLOW_GLOBAL_VARIABLE_STATE = 9,
    FLOW_GLOBAL_VARIABLE_SCREEN_CHANGER_VAR = 10,
    FLOW_GLOBAL_VARIABLE_LAP_COUNT = 11,
    FLOW_GLOBAL_VARIABLE_MISSION = 12,
    FLOW_GLOBAL_VARIABLE_TIME_DIFF = 13,
    FLOW_GLOBAL_VARIABLE_LAST_LAP_TIME = 14
};

// Native global variables

#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/