#!/usr/bin/env python3
"""Validate DBCs, regenerate C/ROS/API/bridge outputs, and record provenance."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

import cantools
from cantools.database.can import c_source


NAMES = ("data_t26", "powertrain_t26", "autonomous_t26")


def regenerate(root: Path, source: Path | None = None) -> None:
    dbc_dir = root / "dbc_signals"
    inputs = source if source is not None else dbc_dir
    # Parse every bus before changing any checked-in file. IDs may repeat across buses.
    contents = {name: (inputs / f"{name}.dbc").read_bytes() for name in NAMES}
    databases = {}
    for name, data in contents.items():
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            text = data.decode("cp1252")  # Kvaser/Vector's legacy DBC encoding.
        databases[name] = cantools.database.load_string(text, database_format="dbc", strict=True)
    hashes = {f"{name}.dbc": hashlib.sha256(data).hexdigest()
              for name, data in contents.items()}
    manifest_path = dbc_dir / "source.json"
    revision = None
    if source is not None:
        # Only label files with a commit when they are tracked and match that revision.
        git = ["git", "-C", str(source)]
        filenames = [f"{name}.dbc" for name in NAMES]
        subprocess.run([*git, "ls-files", "--error-unmatch", *filenames],
                       check=True, stdout=subprocess.DEVNULL)
        subprocess.run([*git, "diff", "--exit-code", "HEAD", "--", *filenames], check=True)
        revision = subprocess.check_output([*git, "rev-parse", "HEAD"], text=True).strip()
    elif manifest_path.exists():
        previous = json.loads(manifest_path.read_text())
        if previous.get("sha256") == hashes:
            revision = previous.get("commit")

    ui = root / "LART_Car_Dashboard_v1/src/ui"
    generated = ui / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    dbc_dir.mkdir(parents=True, exist_ok=True)
    for name, database in databases.items():
        (dbc_dir / f"{name}.dbc").write_bytes(contents[name])
        header, implementation, _, _ = c_source.generate(
            database, name, f"{name}.h", f"{name}.c", f"{name}_fuzzer.c")
        for extension, text in (("h", header), ("c", implementation)):
            # cantools embeds wall-clock time in a comment; keep its version, not the clock.
            text = re.sub(r"(?m)^( \* @brief .*generated by cantools version [^ ]+) .*$",
                          r"\1.", text)
            (generated / f"{name}.{extension}").write_text(text, encoding="utf-8")
    for script in (ui / "generate_dbc_api.py", generated / "generate_can_bridge.py"):
        subprocess.run([sys.executable, str(script)], cwd=root, check=True)
    manifest_path.write_text(json.dumps({
        "repository": "FSLART/T26_DBC", "commit": revision,
        "cantools": cantools.__version__, "sha256": hashes,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path,
                        help="Clean T26_DBC git checkout; otherwise use local dbc_signals")
    args = parser.parse_args()
    regenerate(Path(__file__).resolve().parents[1], args.source_dir)
